apiVersion: v1
kind: Service
metadata:
  labels:
    app: iperf3
  name: my-iperf3
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  #- name: tcp1-port
   # port: 5201
    #protocol: TCP
  #  targetPort: 5201
   # nodePort: 31001
  - name: udf1-port
    port: 5201
    protocol: UDP
    targetPort: 5201
    nodePort: 31001
  selector:
    app: iperf3
