apiVersion: v1
kind: Service
metadata:
  labels:
    app: iperf3
  name: my-iperf3
spec:
  type: NodePort
  ports:
  - name: tcp1-port
    port: 5201
    protocol: TCP
    targetPort: 5201
    nodePort: 31001
  - name: udp1-port
    port: 5201
    protocol: UDP
    targetPort: 5201
    nodePort: 31001
#  - name: sctp1-port
 #   port: 5201
  #  protocol: SCTP
   # targetPort: 5201
  selector:
    app: iperf3

