apiVersion: v1
kind: Service
metadata:
  labels:
    app: iperf3
  name: udp-iperf3
   annotations:
    metallb.universe.tf/allow-shared-ip: "true"
  namespace: iperf3-server
spec:
  type: LoadBalancer
  loadBalancerIP: 196.168.99.241
  externalTrafficPolicy: Local
  ports:
  - name: udp-port
    port: 5201
    protocol: UDP
    targetPort: 5201
  selector:
    app: iperf3
  ---
  apiVersion: v1
kind: Service
metadata:
  labels:
    app: iperf3
  name: tcp-iperf3
   annotations:
    metallb.universe.tf/allow-shared-ip: "true"
  namespace: iperf3-server
spec:
  type: LoadBalancer
  loadBalancerIP: 196.168.99.241
  externalTrafficPolicy: Local
  ports:
  - name: tcp-port
    port: 5201
    protocol: TCP
    targetPort: 5201
  selector:
    app: iperf3
  
    
